# Numpy


"NumPy" é uma abreviação de "Numeric Python".



In [1]:
from array import array

In [2]:
arr = array('i',[1,2,3])
type(arr)

array.array

In [3]:
arr*2

array('i', [1, 2, 3, 1, 2, 3])

In [4]:
arr-1

TypeError: unsupported operand type(s) for -: 'array.array' and 'int'

In [5]:
%pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [7]:
arr = np.array([1,2,3,4])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.shape

(4,)

In [11]:
arr2 = np.array([[1],[2],[3],[4]])
print(arr2)

[[1]
 [2]
 [3]
 [4]]


In [13]:
matriz = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(matriz)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [15]:
arr**2

array([ 1,  4,  9, 16])

In [16]:
arr.dtype

dtype('int64')

In [17]:
arr = np.array([1,2.0,3,4])

In [18]:
arr.dtype

dtype('float64')

In [19]:
arr

array([1., 2., 3., 4.])

In [21]:
arr2 =np.array([['1'],[2],[3],[4]])
arr2.dtype
arr2

array([['1'],
       ['2'],
       ['3'],
       ['4']], dtype='<U21')

In [25]:
tensor = np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,10],[11,12]]])
tensor

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [26]:
matriz

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

In [28]:
matriz2 = matriz*3
matriz2

array([[ 3,  6,  9, 12],
       [ 3,  6,  9, 12],
       [ 3,  6,  9, 12],
       [ 3,  6,  9, 12]])

In [30]:
np.dot(matriz,matriz2)

array([[ 30,  60,  90, 120],
       [ 30,  60,  90, 120],
       [ 30,  60,  90, 120],
       [ 30,  60,  90, 120]])

In [32]:
A = np.array([[0.5,0.5,0.25],
              [0.25,0,0.25],
              [0.25,0.5,0.5]])

hoje = np.array([[1],[0],[0]])
print(hoje)

[[1]
 [0]
 [0]]


In [33]:
for dia in range(1,11):
    print(f'dia> {dia}')
    amanha = np.dot(A,hoje)
    print(amanha)
    hoje=amanha


dia> 1
[[0.5 ]
 [0.25]
 [0.25]]
dia> 2
[[0.4375]
 [0.1875]
 [0.375 ]]
dia> 3
[[0.40625 ]
 [0.203125]
 [0.390625]]
dia> 4
[[0.40234375]
 [0.19921875]
 [0.3984375 ]]
dia> 5
[[0.40039062]
 [0.20019531]
 [0.39941406]]
dia> 6
[[0.40014648]
 [0.19995117]
 [0.39990234]]
dia> 7
[[0.40002441]
 [0.20001221]
 [0.39996338]]
dia> 8
[[0.40000916]
 [0.19999695]
 [0.3999939 ]]
dia> 9
[[0.40000153]
 [0.20000076]
 [0.39999771]]
dia> 10
[[0.40000057]
 [0.19999981]
 [0.39999962]]


## funções padrões

In [34]:
ones = np.ones([3,3])
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [37]:
zeros = np.zeros([3,4,4])
zeros

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [38]:
full = np.full([2,3],10)
full

array([[10, 10, 10],
       [10, 10, 10]])

## Aleatoriedade

In [41]:
aleatorio = np.random.rand(3,4)*10
aleatorio

array([[4.00976477, 7.71303498, 7.07542193, 2.4170637 ],
       [9.89362153, 9.99726424, 1.61269914, 6.40773205],
       [4.38259114, 4.21738759, 9.27576884, 4.79094352]])

In [44]:
aleatorio_int = np.random.randint(0,10,size=(10))
aleatorio_int

array([9, 4, 4, 5, 5, 9, 7, 6, 1, 4])

1 - Crie um array NumPy com 10 elementos inteiros aleatórios no intervalo [0, 100] e exiba os valores e o tipo de dado do array.

In [46]:
aleatorio_int2 = np.random.randint(0,101,size=(10,10))
aleatorio_int2

array([[ 40,  67,  86,  62,  20,  28,   5,  75,  92,  81],
       [ 63,  99,  46,  51,  57,  81,  47,  60,   2,  68],
       [ 44,  75,  83,  25,   2,  20,  84,  12,  91,  60],
       [  3,  29,  68,  90,  49,  78,  94,  56,   6,  81],
       [ 29,  18,  75,  82,  89,  58,  88,  34,  18,   9],
       [ 89,  82,  76,  86,   5,  73,  59,  81,  98,  27],
       [ 49,  36,  54,   7,  79,  71,  20,  62, 100,  31],
       [ 21,  65,  52,   8,  60,  59,  80,  30,  58,  82],
       [ 12,  30,  51,  52,  25,  61,  92,   1,  13,  80],
       [ 69,  37,  54,  99,  34, 100,   0,  13,  67,  76]])

## Indexação

In [47]:
array = np.array([1,2,3,4])

In [ ]:
array

In [59]:
lista = ['cachoro','gato','papagaio']

In [50]:
print(lista[2])

papagaio


In [52]:
arr[3]

4.0

In [53]:
minha_matriz = np.array([[4,7,8],[3,2,1]])
print(minha_matriz)

[[4 7 8]
 [3 2 1]]


In [56]:
print(minha_matriz[0,2])

8


## Slicing

In [64]:
lista[0:3:3]

['cachoro']

In [68]:
array[0:3:1]

array([1, 2, 3])

In [69]:
minha_matriz[1:2,0:]

array([[3, 2, 1]])

In [70]:
minha_matriz[:,0:2]

array([[4, 7],
       [3, 2]])

## Operações de Agregação 

In [71]:
meu_array2 = np.array([1,2,3])

In [77]:
print(f"Soma: {meu_array2.sum()}")
print(f'Média: {int(meu_array2.mean())}')
print(f'Max: {meu_array2.max()}')
print(f'Min: {meu_array2.min()}')
print(f'Variancia: {meu_array2.var()}')
print(f'Desvio Padrão: {meu_array2.std()}')

Soma: 6
Média: 2
Max: 3
Min: 1
Variancia: 0.6666666666666666
Desvio Padrão: 0.816496580927726


### Exercício

Crie uma matriz de 5x5 com valores aleatórios de [0,1) e encontre o valor mínimo, máximo e a média da matriz.

In [80]:
np.random.seed(42)

matriz = np.random.rand(5,5)

print(matriz)
print(f'Valor Mínimo: {matriz.min().round(2)}')
print(f'Valor Máximo: {matriz.max().round(2)}')
print(f'Valor Média Aritmética: {matriz.mean().round(2)}')


[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
 [0.15599452 0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497]
 [0.18340451 0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]]
Valor Mínimo: 0.02
Valor Máximo: 0.97
Valor Média Aritmética: 0.44


In [83]:
float_arr = np.array([1.9,1.2,2.0])
float_arr = float_arr*2
print(float_arr)
float_arr.astype(int)

[3.8 2.4 4. ]


array([3, 2, 4])

### Exercício

Crie um array com 10 elementos aleatórios no intervalo [0, 1]. Em seguida, crie um novo array com os elementos do primeiro array multiplicados por 10 e convertidos para inteiro.

In [86]:
np.random.seed(42)
array_aleatorio = np.random.rand(10)
print(array_aleatorio)
array_int = array_aleatorio*10
array_int = array_int.astype(int)
print(array_int)

[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258]
[3 9 7 5 1 1 0 8 6 7]
